FROM node:14.15

LABEL maintainer="manishprivet808@gmail.com"

RUN mkdir -p /app

WORKDIR /app

COPY . .

ARG DB_HOST
ARG DB_PORT
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_NAME
ARG SMTP_MAIL_USER
ARG SMTP_MAIL_PASSWORD
ARG SMTP_SERVER

ENV DB_HOST=${DB_HOST}
ENV DB_NAME=${DB_NAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_PORT=${DB_PORT}
ENV DB_USERNAME=${DB_USERNAME}
ENV SMTP_MAIL_PASSWORD=${SMTP_MAIL_PASSWORD}
ENV SMTP_MAIL_USER=${SMTP_MAIL_USER}
ENV SMTP_SERVER=${SMTP_SERVER}

ENV NODE_ENV=production
ENV PORT=80

RUN npm install --only=prod

RUN npm run build

EXPOSE 80

CMD node dist/index.js